apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rc-mycat
  labels:
    name: mycat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mycat
    spec:
      containers:
      - name: mycat
        image: 10.0.0.33:60080/alaudaorg/mycat-docker:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_USER
            value: 'root'
          - name: MYSQL_PASSWORD
            value: 'demo'
          - name: DB_NAME
            value: 'demo'
          - name: LOG_LEVEL
            value: 'debug'
        ports:
        - containerPort: 8066
---
apiVersion: v1
kind: Service
metadata:
  name: mycat
spec:
  ports:
  - name: client 
    port: 8066
    protocol: TCP
  - name: admin
    port: 9066
    protocol: TCP
  selector:
    name: mycat
  type:
     NodePort
